default_language_version:
  # pylint-odoo does not (yet) support Python 3.10.
  python: python3.10

repos:

# black
- repo: https://github.com/ambv/black
  rev: 23.1.0
  hooks:
  - id: black
    language_version: python3.10
    exclude: __openerp__.py|__manifest__.py|odoo/external-src/

# pylint
- repo: https://github.com/pycqa/pylint
  rev: v2.17.5
  hooks:
    - id: pylint
      language_version: python3.10
      exclude: templates/|static/|flaskr/
      args: [flaskr, --disable=import-error]
# flake8
-   repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
    -   id: flake8

