default_language_version:
  # pylint-odoo does not (yet) support Python 3.10.
  python: python3.10

repos:

# black
- repo: https://github.com/ambv/black
  rev: 23.1.0
  hooks:
  - id: black
    language_version: python3.10
    exclude: __openerp__.py|__manifest__.py|odoo/external-src/

# pylint
- repo: https://github.com/pycqa/pylint
  rev: v2.17.5
  hooks:
    - id: pylint
      args: [flaskr, --disable=import-error]
